### ISSUE TITLE
observeInLifecycle is deprecated

### ISSUE THREAD

**Issue by naj147** [k0siara/AndroidMVIExample#1]
for dealing with StateFlows now, it is recommended to use flowWithLifeCycle instead of observeInLifecycle, as this last one has been deprecated. Looking forward to see an update to your example repo, it has served me well.

**Comment by k0siara** [comment]
Hi Abel, observeInLifecycle is not deprecated, as it is my custom extension method. See it here: https://github.com/k0siara/AndroidMVIExample/blob/master/app/src/main/java/com/patrykkosieradzki/androidmviexample/utils/FlowObserver.kt 😄
